phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 349268017107.dkr.ecr.eu-central-1.amazonaws.com
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t repo-2 .
      - docker tag repo-2:latest 349268017107.dkr.ecr.eu-central-1.amazonaws.com/repo-2:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker image...
      - docker push 349268017107.dkr.ecr.eu-central-1.amazonaws.com/repo-2:latest
